site:
  name: TrenDropp

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  forward-headers-strategy: framework

spring:
  messages:
    encoding: UTF-8
    basename: messages
  thymeleaf:
    encoding: UTF-8

crawler:
  repeat-count: 3

gemini:
  api:
    key: ${API_KEY}
