site:
  name: TrenDropp

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  forward-headers-strategy: framework

spring:
  messages:
    encoding: UTF-8
    basename: messages
  thymeleaf:
    encoding: UTF-8

crawler:
  repeat-count: 3

gemini:
  api:
    key: ${API_KEY}

x-api:
  bearer-token: AAAAAAAAAAAAAAAAAAAAAL155gEAAAAAK7gOn0AfgJcFEoGiBuVOaKtC8v0%3Dsl8OhIzJ7l31J952VunhNvMareqJYDu34ag2m4FgLqrw0ovyRU
  base-url: "https://api.x.com/2"
  max-result: 1