spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/celebdb
    username: admin
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gemini:
  api:
    key: ${API_KEY}


crawler:
  repeat-count: 10