site:
  name: TrenDropp

server:
  port: 8080
spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: messages



crawler:
  repeat-count: 10

gemini:
  api:
    key: ${API_KEY}